### ISSUE TITLE
Specflow scenario steps are shown as unresolved for an existing project

### ISSUE THREAD

**Issue by mickvikt** [Socolin/resharper-specflow#7] opened 2021-01-31 10:48 UTC
Hello,
I'm really happy about your work in developing this plugin. It is really needed, thank you.

I have an issue with our existing project having Specflow tests. They have been done in Visual Studio. The problem is that steps are being marked as "Unresolved step" in Rider. Is this because the steps and scenarios have been created not by using your plug-in?

Or does it have something to do with a message, requiring to disable bundled Cucumber/Gherkin plugins after the installation?

Thank you,
Viktoras

**Comment by hryz** [comment] 2021-01-31 17:56
First of all, you are hero! 
I was going to do the same and I even started, but when I looked at the original SpecFlow code and how large the code base is I was super discouraged and abandoned this idea. Luckily, you are more optimistic than me 😁.

Here are my 2 cents that might help diagnosing the issue.
- I ran into the issue that _most_ of the step definitions are not bounded to their usages. 
- If I use the quick fix it suggests only 4 files with step definitions out of 10+ files to put a new definition into.
- When I move some of the definitions from the unindexed files to any of those 4 indexed files then Go to definition / Find Usages start working fine.
- It seems like the daemon processes for those unindexed files with definition crashed due to unexpected input and didn't finish indexing.
In the logs I found only 1 error:
```
//backend-err.log

--- EXCEPTION #1/2 [KeyNotFoundException]
Message = “The given key 'Unknown' was not present in the dictionary.”
ExceptionPath = Root.InnerException
ClassName = System.Collections.Generic.KeyNotFoundException
Data.ThreadLocalDebugInfo = ReentrancyGuardTaskScheduler::QueueTask
HResult = COR_E_KEYNOTFOUND=80131577
Source = System.Private.CoreLib
StackTraceString = “
  at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
     at ReSharperPlugin.SpecflowRiderPlugin.Caching.StepsUsages.SpecflowStepsUsagesCache.AddToLocalCache(IPsiSourceFile sourceFile, SpecflowStepsUsagesCacheEntries cacheItems) in /home/socolin/RiderProjects/resharper-specflow/src/dotnet/ReSharperPlugin.SpecflowRiderPlugin/Caching/StepsUsages/SpecflowStepsUsagesCache.cs:line 72
     at ReSharperPlugin.SpecflowRiderPlugin.Caching.StepsUsages.SpecflowStepsUsagesCache.Merge(IPsiSourceFile sourceFile, Object builtPart) in /home/socolin/RiderProjects/resharper-specflow/src/dotnet/ReSharperPlugin.SpecflowRiderPlugin/Caching/StepsUsages/SpecflowStepsUsagesCache.cs:line 55
     at JetBrains.ReSharper.Psi.Caches.Jobs.JobUpdateProjectFiles.MergeProjectFile(IPsiSourceFile sourceFile, Int64 timestamp, IList`1 part)
     at JetBrains.ReSharper.Psi.Caches.Jobs.JobUpdateProjectFiles.<>c__DisplayClass14_0.<ExecuteUpdate>b__2(KeyValuePair`2 pair)
     at JetBrains.ReSharper.Psi.Caches.Jobs.CacheJobService2.<>c__DisplayClass42_0`1.<ExecuteSplittedWriteActivity>b__3()
     at JetBrains.Util.Logging.Logger.Catch(Action action)
”

```

**Comment by Socolin** [comment] 2021-01-31 21:56
Hello,

> I have an issue with our existing project having Specflow tests. They have been done in Visual Studio. The problem is that steps are being marked as "Unresolved step" in Rider. Is this because the steps and scenarios have been created not by using your plug-in?

The plugin should be able to found links between steps and steps definitions automatically if it don't, I missed something and an example of the step (just the line `Given ...`), and the step definition (The method + Attribute, without the content) would help me understand the problem.

 > If I use the quick fix it suggests only 4 files with step definitions out of 10+ files to put a new definition into.
Can you give me the skeleton of one of the missing classes ? (using + attribute + class without the methods body)

I'll take a look for the error you reported. Thanks

**Comment by Socolin** [comment] 2021-01-31 22:34
@hryz hryz

So about the error, my current implementation seems to failed to determine the kind of one of you step and it crash the whole cache process.

I pushed a fix, can you try the version of the plugin available when the build complete in [github action](https://github.com/Socolin/resharper-specflow/actions/runs/526098325) 

Could you give it a try and give me the new error log that should contains more details, with the concerned step.

**Comment by hryz** [comment] 2021-01-31 22:37
Sure, I'll try it tomorrow and will share the log in case of issues.
Thank you again!

**Comment by mickvikt** [comment] 2021-01-31 22:52
> Hello,
> 
> > I have an issue with our existing project having Specflow tests. They have been done in Visual Studio. The problem is that steps are being marked as "Unresolved step" in Rider. Is this because the steps and scenarios have been created not by using your plug-in?
> 
> The plugin should be able to found links between steps and steps definitions automatically if it don't, I missed something and an example of the step (just the line `Given ...`), and the step definition (The method + Attribute, without the content) would help me understand the problem.
> 
> > If I use the quick fix it suggests only 4 files with step definitions out of 10+ files to put a new definition into.
> > Can you give me the skeleton of one of the missing classes ? (using + attribute + class without the methods body)
> 
> I'll take a look for the error you reported. Thanks

**Comment by mickvikt** [comment] 2021-01-31 23:03
> The plugin should be able to found links between steps and steps definitions automatically if it don't, I missed something and an example of the step (just the line `Given ...`), and the step definition (The method + Attribute, without the content) would help me understand the problem.

Here are the examples:

Step:  `When ActiveMQ is called`
Step Definition:
```
[When(@"ActiveMQ is called")]
public void WhenActiveMQIsCalled()
{}

```
or
Step: `Given Schedule exists in Snowflake`
Step definition
```
[Given(@"Schedule exists in Snowflake")]
public void GivenScheduleExists()
{}
```
Also, .feature files and classes, encapsulating step definitions are being kept in seperate folders, could that influence something?

**Comment by Socolin** [comment] 2021-01-31 23:47
Those steps should works:
- Do you have any red icon in the bottom status bar of the Rider ? (if yes click and copy paste the error)
![image](https://user-images.githubusercontent.com/539620/106401828-440ffa80-63f4-11eb-97c5-49231977c6d7.png)
- Does you step definitions are following this skeleton or do you have any additional imbrication (intermediate classes, region etc.. ?) ?
```
using ...;

namespace Test
{
    [Binding]
    public class TestSteps
    {
        [Given(@"Schedule exists in Snowflake")]
        public void GivenScheduleExists()
        {
        }

        [When(@"ActiveMQ is called")]
        public void WhenActiveMQIsCalled()
        {
        }
    }
}
```

**Comment by Socolin** [comment] 2021-02-01 01:35
Ok I've found a bug when openning for the first time a solution some field I was depending on are not available. Then it was not able to build a cache with all step definitions.

I'm not sure this is the problem but it may be.

I've pushed a fix, could you try with the artifact when available here ? https://github.com/Socolin/resharper-specflow/actions/runs/526360460
- Download the artifact
- Extract the plugin.zip from the artifact archive
- Then add the plugin from the .zip
![image](https://user-images.githubusercontent.com/539620/106405288-b2a88480-6403-11eb-814c-335307f70183.png)

**Comment by hryz** [comment] 2021-02-01 12:11
Here is a small update from my side.

I've downloaded the new version and installed it. It extended logging and I saw the issues in some feature files. They had a step starting with `And` as the first step of the scenario. When I fixed them, cleared logs, and restarted Rider no more errors were in `backend-err.log`. However, the binding issue was _not_ fixed.

I've tried removing the contents from the step definitions and keeping only regex. It didn't work out.
I've tried simplifying regexes replacing the `((?i)\bRegular|Main\b)` word starting magic. It didn't work out.
Then I simply copied all the classes from all the files with step definitions into a single file that is listed in the quick fix and **it worked**. No modification of the code was applied. The contents were copied as is, even keeping them in separate classes, just putting them into a "proper" file.

If this is location related issue the project structure and file names might give some clues.
The location of features: `./Tests/Features/Foo.feature`
The location of the step definitions that didn't work: `./Tests/StepDefinitions/BarSteps.cs`
The location of the step definitions that worked out: `./Core/Utils/Baz.cs`

BTW, forgot to mention, the platform is Mac OS 11.1, SpecFlow 3.5.5 (+ NUnit + MsBuild generation)

**Comment by Socolin** [comment] 2021-02-01 14:20
> I've downloaded the new version and installed it. It extended logging and I saw the issues in some feature files. They had a step starting with `And` as the first step of the scenario. When I fixed them, cleared logs, and restarted Rider no more errors were in `backend-err.log`. However, the binding issue was _not_ fixed.

Ok I've fixed the bug of `And` in the last commit, https://github.com/Socolin/resharper-specflow/issues/7#issuecomment-770502998

> 
> I've tried removing the contents from the step definitions and keeping only regex. It didn't work out.
> I've tried simplifying regexes replacing the `((?i)\bRegular|Main\b)` word starting magic. It didn't work out.
> Then I simply copied all the classes from all the files with step definitions into a single file that is listed in the quick fix and **it worked**. No modification of the code was applied. The contents were copied as is, even keeping them in separate classes, just putting them into a "proper" file.
> 
> If this is location related issue the project structure and file names might give some clues.
> The location of features: `./Tests/Features/Foo.feature`
> The location of the step definitions that didn't work: `./Tests/StepDefinitions/BarSteps.cs`
> The location of the step definitions that worked out: `./Core/Utils/Baz.cs`
> 
> BTW, forgot to mention, the platform is Mac OS 11.1, SpecFlow 3.5.5 (+ NUnit + MsBuild generation)


I also fixed other issue about step definition detection in this build, can you tests that ?

If problem persist I would like a simple sample project to reproduce and fix the bug. If you cannot provide a sample I'll try to add debug log to understand why it's not working.

**Comment by hryz** [comment] 2021-02-01 15:35
I've found it!
If you add a `using` within a namespace and outside of the namespace the plugin stops indexing these step definitions.

**Comment by mickvikt** [comment] 2021-02-01 16:49
> I've found it!
> If you add a `using` within a namespace and outside of the namespace the plugin stops indexing these step definitions.

Could very well be, since all `using `statements in my project are inside the namespace, as per StyleCop rule.

**Comment by mickvikt** [comment] 2021-02-01 16:59
Yes, I can confirm, when I moved the using statements out of namespaces in some of my step classes, steps started to get discovered.

Great detective work, @hryz!

**Comment by Socolin** [comment] 2021-02-01 22:22
Can you check if the version 1.2.3 fixed the bug about `Unresolved step` ?

**Comment by hryz** [comment] 2021-02-01 22:26
Yes, it did. Great work! 🎉

**Comment by mickvikt** [comment] 2021-02-02 19:40
@Socolin Everything works as expected for me too. Thank you very much. This is really appreciated, can't wait to use this for work.

I guess we can close the issue now?

**Comment by Socolin** [comment] 2021-02-03 23:56
I'm closing then

**Closed by Socolin** 2021-02-03 23:56 UTC
